import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useNavigate } from 'react-router-dom';
import {
  Rocket,
  Sparkles,
  Globe2,
  TrendingUp,
  Cpu,
  Camera,
  Radio,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  Sun,
  Moon,
  Zap,
  Palette,
  Users,
  Music,
  Disc,
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { useTheme, Vibe, UserRole, Theme, VisualStyle } from '../../context/ThemeContext';

type SlideKind =
  | 'hero'
  | 'pitch'
  | 'feature'
  | 'appearance'
  | 'portal';

interface BaseSlide {
  id: string;
  kind: SlideKind;
}

const FEATURES = [
  {
    id: 'distribution',
    tag: 'PROTOCOL_01',
    title: 'Smart Distribution',
    desc: 'One upload. Every major DSP. Spotify, Apple, YouTube Music, Tidal, SoundCloud — distributed in parallel with live status telemetry on every platform.',
    icon: Rocket,
    accent: 'from-orange-500/20 to-transparent',
  },
  {
    id: 'ai',
    tag: 'PROTOCOL_02',
    title: 'AI Content Engine',
    desc: 'Cover art, video teasers, viral TikTok hooks, UGC scripts and promo packs — generated by neural pipelines tuned to your release.',
    icon: Sparkles,
    accent: 'from-blue-500/20 to-transparent',
  },
  {
    id: 'network',
    tag: 'PROTOCOL_03',
    title: 'Verified Creator Network',
    desc: 'Direct relays into a vetted network of influencers, micro-creators and DJs. Send packs, track posts, measure real reach — no middlemen.',
    icon: Globe2,
    accent: 'from-purple-500/20 to-transparent',
  },
  {
    id: 'lvrn',
    tag: 'PROTOCOL_04',
    title: 'LVRN Direct Access',
    desc: 'Submit to the LVRN A&R inner circle. Real feedback, strategic guidance, and direct lines to a label that has scaled platinum careers.',
    icon: TrendingUp,
    accent: 'from-green-500/20 to-transparent',
  },
];

const COLORS: { id: Vibe; name: string; hex: string; tagline: string }[] = [
  { id: 'TECHNICAL_ORANGE', name: 'Tech Orange', hex: '#FF4D00', tagline: 'Original manifest energy' },
  { id: 'LVRN_GREEN', name: 'LVRN Green', hex: '#acec00', tagline: 'Direct executive clearance' },
  { id: 'NEON_PINK', name: 'Neon Pink', hex: '#ff00ff', tagline: 'Hyperpop sonic frequency' },
  { id: 'CYBER_BLUE', name: 'Cyber Blue', hex: '#00f2ff', tagline: 'Cold digital logic' },
  { id: 'MONO_WHITE', name: 'Mono Archive', hex: '#ffffff', tagline: 'Minimal redacted aesthetic' },
];

const PORTALS: {
  id: UserRole;
  name: string;
  tagline: string;
  desc: string;
  icon: React.ElementType;
  route: string;
  perks: string[];
}[] = [
  {
    id: 'ARTIST',
    name: 'Artist Core',
    tagline: 'I make the music',
    desc: 'Full distribution, AI assets studio, campaign OS, and direct LVRN A&R submission.',
    icon: Music,
    route: '/signup',
    perks: ['Distribute to all DSPs', 'AI cover & video', 'A&R submission', 'Royalty splits'],
  },
  {
    id: 'INFLUENCER',
    name: 'Creator Relay',
    tagline: 'I create content',
    desc: 'Accept paid missions from artists, post on TikTok / Reels / Shorts, get paid per verified post.',
    icon: Camera,
    route: '/login',
    perks: ['Paid campaign missions', 'Performance analytics', 'Instant payouts', 'Brand match score'],
  },
  {
    id: 'DJ',
    name: 'Vibe Selecta',
    tagline: 'I move the dance floor',
    desc: 'Receive curated DJ promo packs, stem files, edits, and direct feedback loops to artists.',
    icon: Disc,
    route: '/login',
    perks: ['Exclusive DJ packs', 'Stems & edits access', 'Feedback channel', 'Chart signal data'],
  },
];

const SLIDES: BaseSlide[] = [
  { id: 'hero', kind: 'hero' },
  { id: 'pitch', kind: 'pitch' },
  ...FEATURES.map((f) => ({ id: f.id, kind: 'feature' as SlideKind })),
  { id: 'appearance', kind: 'appearance' },
  { id: 'portal', kind: 'portal' },
];

const slideVariants = {
  enter: (dir: number) => ({ x: dir > 0 ? 80 : -80, opacity: 0 }),
  center: { x: 0, opacity: 1 },
  exit: (dir: number) => ({ x: dir > 0 ? -80 : 80, opacity: 0 }),
};

export const WelcomeScreen: React.FC<{ onComplete: () => void }> = ({ onComplete }) => {
  const navigate = useNavigate();
  const { vibe, setVibe, theme, toggleTheme, role, setRole, visualStyle, setVisualStyle } = useTheme();

  const [index, setIndex] = useState(0);
  const [direction, setDirection] = useState(1);

  const slide = SLIDES[index];
  const total = SLIDES.length;

  const next = () => {
    if (index < total - 1) {
      setDirection(1);
      setIndex((i) => i + 1);
    }
  };

  const prev = () => {
    if (index > 0) {
      setDirection(-1);
      setIndex((i) => i - 1);
    }
  };

  const finish = (_route: string) => {
    // Mark welcome complete (sets dropkast_welcome_seen) and route to /login.
    // Login detects the flag and skips its own portal step — no duplicate.
    // The post-auth redirect into the actual portal landing happens after sign-in.
    onComplete();
    navigate('/login');
  };

  const featureForSlide = useMemo(() => {
    if (slide.kind !== 'feature') return null;
    return FEATURES.find((f) => f.id === slide.id) || FEATURES[0];
  }, [slide]);

  const colorObj = COLORS.find((c) => c.id === vibe) ?? COLORS[0];

  return (
    <div
      className="welcome-container fixed inset-0 z-[200] flex flex-col bg-black text-white overflow-hidden"
      style={{ '--color-primary': colorObj.hex } as React.CSSProperties}
    >
      {/* Background */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute inset-0 technical-grid opacity-[0.04]" />
        <motion.div
          key={colorObj.hex}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6 }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] rounded-full blur-[140px]"
          style={{ background: `radial-gradient(circle, ${colorObj.hex}22 0%, transparent 70%)` }}
        />
      </div>

      {/* Top bar */}
      <header className="relative z-10 flex items-center justify-between px-4 sm:px-8 py-4 sm:py-6 gap-3">
        <div className="flex items-center gap-2 sm:gap-3 min-w-0">
          <div className="w-6 h-6 border flex items-center justify-center p-0.5 shrink-0" style={{ borderColor: colorObj.hex }}>
            <div className="w-full h-full" style={{ backgroundColor: colorObj.hex }} />
          </div>
          <span className="text-sm font-mono font-black tracking-tighter italic">DROPKAST</span>
          <span className="hidden sm:inline text-[9px] font-mono font-black text-white/30 tracking-[0.3em] uppercase italic ml-2">
            v3.0.1 — Onboarding
          </span>
        </div>

        <button
          onClick={() => {
            onComplete();
            navigate('/login');
          }}
          className="text-[10px] font-mono font-black text-white/30 hover:text-white tracking-[0.3em] uppercase italic flex items-center gap-2 group transition-colors shrink-0"
        >
          <span>Skip</span>
          <ChevronRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
        </button>
      </header>

      {/* Progress */}
      <div className="relative z-10 px-4 sm:px-8 mb-2">
        <div className="flex gap-1 max-w-5xl mx-auto">
          {SLIDES.map((s, i) => (
            <div key={s.id} className="flex-1 h-[3px] bg-white/5 overflow-hidden">
              <motion.div
                className="h-full"
                style={{ backgroundColor: colorObj.hex }}
                initial={{ width: '0%' }}
                animate={{ width: i < index ? '100%' : i === index ? '100%' : '0%' }}
                transition={{ duration: 0.4 }}
              />
            </div>
          ))}
        </div>
        <div className="flex items-center justify-between max-w-5xl mx-auto mt-3 text-[9px] font-mono font-black text-white/30 tracking-[0.3em] uppercase italic">
          <span>
            Step {String(index + 1).padStart(2, '0')} / {String(total).padStart(2, '0')}
          </span>
          <span>{slide.kind.toUpperCase()}</span>
        </div>
      </div>

      {/* Slide body */}
      <main className="relative z-10 flex-1 overflow-y-auto px-4 sm:px-8 pb-32 overscroll-contain">
        <div className="max-w-5xl mx-auto h-full flex items-center justify-center py-6 sm:py-8">
          <AnimatePresence mode="wait" custom={direction}>
            <motion.div
              key={slide.id}
              custom={direction}
              variants={slideVariants}
              initial="enter"
              animate="center"
              exit="exit"
              transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
              className="w-full"
            >
              {slide.kind === 'hero' && <HeroSlide accent={colorObj.hex} />}

              {slide.kind === 'pitch' && <PitchSlide accent={colorObj.hex} />}

              {slide.kind === 'feature' && featureForSlide && (
                <FeatureSlide feature={featureForSlide} accent={colorObj.hex} />
              )}

              {slide.kind === 'appearance' && (
                <AppearanceSlide
                  vibe={vibe}
                  onVibe={setVibe}
                  theme={theme}
                  onTheme={toggleTheme}
                  visualStyle={visualStyle}
                  onVisualStyle={setVisualStyle}
                  colors={COLORS}
                  accent={colorObj.hex}
                />
              )}

              {slide.kind === 'portal' && (
                <PortalSlide
                  selected={role}
                  onSelect={setRole}
                  onConfirm={(r) => {
                    setRole(r);
                    const portal = PORTALS.find((p) => p.id === r) ?? PORTALS[0];
                    finish(portal.route);
                  }}
                  accent={colorObj.hex}
                />
              )}
            </motion.div>
          </AnimatePresence>
        </div>
      </main>

      {/* Footer nav */}
      <footer className="absolute bottom-0 left-0 right-0 z-10 border-t border-white/5 bg-black/80 backdrop-blur-xl">
        <div className="max-w-5xl mx-auto px-4 sm:px-8 py-4 sm:py-5 flex items-center justify-between gap-3">
          <button
            onClick={prev}
            disabled={index === 0}
            className={cn(
              'h-11 sm:h-12 px-4 sm:px-6 border border-white/10 text-[10px] font-mono font-black uppercase italic tracking-[0.2em] sm:tracking-[0.3em] flex items-center gap-2 sm:gap-3 transition-all shrink-0',
              index === 0
                ? 'opacity-30 cursor-not-allowed'
                : 'hover:border-white hover:text-white text-white/50',
            )}
          >
            <ChevronLeft className="w-4 h-4" />
            <span className="hidden sm:inline">Back</span>
          </button>

          <div className="hidden md:flex items-center gap-2 text-[9px] font-mono text-white/20 uppercase tracking-[0.3em] italic">
            <Zap className="w-3 h-3" style={{ color: colorObj.hex }} />
            <span>Press Next to continue</span>
          </div>

          {slide.kind !== 'portal' ? (
            <button
              onClick={next}
              className="h-11 sm:h-12 px-5 sm:px-8 text-[10px] font-mono font-black uppercase italic tracking-[0.2em] sm:tracking-[0.3em] flex items-center gap-2 sm:gap-3 text-black transition-all hover:scale-[1.03]"
              style={{ backgroundColor: colorObj.hex }}
            >
              {index === 0 ? 'Begin' : 'Next'}
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button
              onClick={() => {
                const portal = PORTALS.find((p) => p.id === role) ?? PORTALS[0];
                finish(portal.route);
              }}
              className="h-11 sm:h-12 px-4 sm:px-8 text-[10px] font-mono font-black uppercase italic tracking-[0.2em] sm:tracking-[0.3em] flex items-center gap-2 sm:gap-3 text-black transition-all hover:scale-[1.03]"
              style={{ backgroundColor: colorObj.hex }}
            >
              <span className="hidden sm:inline">Enter Portal</span>
              <span className="inline sm:hidden">Enter</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      </footer>
    </div>
  );
};

/* ---------------- Slide bodies ---------------- */

const HeroSlide: React.FC<{ accent: string }> = ({ accent }) => (
  <div className="text-center md:text-left space-y-6 sm:space-y-8">
    <div className="flex items-center justify-center md:justify-start gap-3">
      <div className="h-[1px] w-10" style={{ backgroundColor: accent }} />
      <span className="text-[9px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
        System Initiated
      </span>
    </div>
    <h1 className="text-5xl sm:text-6xl md:text-7xl font-black italic uppercase tracking-tighter font-mono leading-[0.85]">
      <span className="block">DROP</span>
      <span className="block" style={{ color: accent }}>KAST</span>
    </h1>
    <p className="max-w-2xl text-sm sm:text-base md:text-lg text-white/60 leading-relaxed font-medium">
      The AI-powered command deck for independent music. Distribute to every DSP, generate viral content, deploy
      verified creator networks, and submit straight to LVRN A&R — all from one launchpad.
    </p>
    <div className="flex flex-wrap items-center justify-center md:justify-start gap-x-4 gap-y-2 text-[9px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic">
      <span>Distribution</span>
      <span style={{ color: accent }}>•</span>
      <span>AI Content</span>
      <span style={{ color: accent }}>•</span>
      <span>Creator Network</span>
      <span style={{ color: accent }}>•</span>
      <span>A&R Pipeline</span>
    </div>
  </div>
);

const PitchSlide: React.FC<{ accent: string }> = ({ accent }) => (
  <div className="space-y-8">
    <div className="space-y-3">
      <span className="text-[9px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
        What Is DropKast?
      </span>
      <h2 className="text-3xl sm:text-4xl md:text-5xl font-black italic uppercase tracking-tighter font-mono leading-none">
        Music distribution<br /> built for the<br />
        <span style={{ color: accent }}>algorithm era.</span>
      </h2>
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      {[
        {
          k: 'For Artists',
          v: 'Upload once. Hit every DSP. Get a campaign OS that thinks for you.',
          icon: Rocket,
        },
        {
          k: 'For Creators',
          v: 'Get paid for posts. Match with the right releases. Track every metric.',
          icon: Sparkles,
        },
        {
          k: 'For DJs',
          v: 'First-look promo packs, stems, and edits direct from the source.',
          icon: Radio,
        },
      ].map((b) => (
        <div key={b.k} className="manifest-card p-5 border-white/10 bg-white/[0.02]">
          <b.icon className="w-5 h-5 mb-3" style={{ color: accent }} />
          <div className="text-[9px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic mb-1.5">
            {b.k}
          </div>
          <p className="text-xs sm:text-sm text-white/80 leading-relaxed">{b.v}</p>
        </div>
      ))}
    </div>
  </div>
);

const FeatureSlide: React.FC<{ feature: typeof FEATURES[number]; accent: string }> = ({ feature, accent }) => {
  const Icon = feature.icon;
  return (
    <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
      <div className="md:col-span-5 flex justify-center md:justify-start">
        <div
          className="relative w-32 h-32 sm:w-40 sm:h-40 md:w-48 md:h-48 border-2 flex items-center justify-center"
          style={{ borderColor: accent }}
        >
          <div
            className="absolute inset-0 opacity-10"
            style={{ background: `radial-gradient(circle, ${accent} 0%, transparent 70%)` }}
          />
          <Icon className="w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 relative z-10" style={{ color: accent }} />
          <div
            className="absolute -top-2.5 -left-2.5 text-[9px] font-mono font-black uppercase tracking-[0.3em] italic px-2 py-1 bg-black"
            style={{ color: accent }}
          >
            {feature.tag}
          </div>
        </div>
      </div>

      <div className="md:col-span-7 space-y-4 sm:space-y-5">
        <h2 className="text-3xl sm:text-4xl md:text-5xl font-black italic uppercase tracking-tighter font-mono leading-[0.9]">
          {feature.title}
        </h2>
        <p className="text-sm sm:text-base md:text-lg text-white/60 leading-relaxed font-medium">{feature.desc}</p>
        <div className="flex items-center gap-3 text-[9px] font-mono font-black uppercase tracking-[0.4em] italic" style={{ color: accent }}>
          <Zap className="w-3.5 h-3.5" />
          <span>Ready to deploy</span>
        </div>
      </div>
    </div>
  );
};

/**
 * Combined "Appearance" slide. Mirrors Settings → Appearance: compact
 * color swatches, dark/light toggle, and visual style picker — all on
 * one slide so onboarding doesn't drag.
 */
const VISUAL_STYLES: { id: VisualStyle; label: string }[] = [
  { id: 'default', label: 'Technical' },
  { id: 'neumorphism', label: 'Neumorphism' },
  { id: 'material', label: 'Material' },
  { id: 'brutalism', label: 'Brutalism' },
  { id: 'skeuomorphism', label: 'Skeuomorphic' },
  { id: 'minimalist', label: 'Minimal' },
  { id: 'glassmorphism', label: 'Glass' },
];

const AppearanceSlide: React.FC<{
  vibe: Vibe;
  onVibe: (v: Vibe) => void;
  theme: Theme;
  onTheme: () => void;
  visualStyle: VisualStyle;
  onVisualStyle: (s: VisualStyle) => void;
  colors: typeof COLORS;
  accent: string;
}> = ({ vibe, onVibe, theme, onTheme, visualStyle, onVisualStyle, colors, accent }) => {
  const setTheme = (target: Theme) => {
    if (theme !== target) onTheme();
  };
  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Palette className="w-3.5 h-3.5" style={{ color: accent }} />
          <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
            Personalize
          </span>
        </div>
        <h2 className="text-2xl sm:text-3xl md:text-4xl font-black italic uppercase tracking-tighter font-mono leading-none">
          Make it yours.
        </h2>
        <p className="text-xs sm:text-sm text-white/50 max-w-xl">
          Color, mode, style — change anytime from Settings.
        </p>
      </div>

      {/* Color */}
      <div className="space-y-2">
        <div className="text-[9px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic">
          Color · {colors.find((c) => c.id === vibe)?.name}
        </div>
        <div className="grid grid-cols-5 gap-2">
          {colors.map((c) => {
            const active = vibe === c.id;
            return (
              <button
                key={c.id}
                onClick={() => onVibe(c.id)}
                className={cn(
                  'aspect-square relative border transition-all',
                  active ? 'scale-105 border-2' : 'border border-white/10 hover:border-white/30',
                )}
                style={{
                  background: `linear-gradient(135deg, ${c.hex}, ${c.hex}88)`,
                  borderColor: active ? c.hex : undefined,
                  boxShadow: active ? `0 0 0 2px ${c.hex}66` : undefined,
                }}
                aria-label={c.name}
                title={c.name}
              >
                {active && (
                  <CheckCircle2
                    className="absolute inset-0 m-auto w-3.5 h-3.5"
                    style={{ color: '#000', filter: 'drop-shadow(0 0 2px rgba(255,255,255,0.5))' }}
                  />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Theme */}
      <div className="space-y-2">
        <div className="text-[9px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic">
          Mode
        </div>
        <div className="grid grid-cols-2 gap-2">
          {([
            { id: 'dark' as Theme, name: 'Dark', icon: Moon },
            { id: 'light' as Theme, name: 'Light', icon: Sun },
          ]).map((t) => {
            const active = theme === t.id;
            const Icon = t.icon;
            return (
              <button
                key={t.id}
                onClick={() => setTheme(t.id)}
                className={cn(
                  'flex items-center justify-center gap-2 py-2.5 border transition-all text-[11px] font-mono font-black uppercase italic tracking-widest',
                  active ? 'bg-white/5' : 'hover:bg-white/[0.03] text-white/60',
                )}
                style={active ? { borderColor: accent, color: accent } : { borderColor: 'rgba(255,255,255,0.1)' }}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{t.name}</span>
                {active && <CheckCircle2 className="w-3 h-3" />}
              </button>
            );
          })}
        </div>
      </div>

      {/* Visual style */}
      <div className="space-y-2">
        <div className="text-[9px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic">
          Visual style
        </div>
        <div className="grid grid-cols-3 sm:grid-cols-4 lg:grid-cols-7 gap-2">
          {VISUAL_STYLES.map((s) => {
            const active = visualStyle === s.id;
            return (
              <button
                key={s.id}
                onClick={() => onVisualStyle(s.id)}
                className={cn(
                  'py-2 px-2 border transition-all text-[10px] font-mono font-black uppercase italic tracking-tight text-center',
                  active ? 'bg-white/5' : 'hover:bg-white/[0.03] text-white/60',
                )}
                style={active ? { borderColor: accent, color: accent } : { borderColor: 'rgba(255,255,255,0.1)' }}
              >
                {s.label}
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
};

const PortalSlide: React.FC<{
  selected: UserRole;
  onSelect: (r: UserRole) => void;
  onConfirm: (r: UserRole) => void;
  accent: string;
}> = ({ selected, onSelect, onConfirm, accent }) => (
  <div className="space-y-10">
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <Users className="w-4 h-4" style={{ color: accent }} />
        <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
          Choose Your Portal
        </span>
      </div>
      <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-none">
        Which side of the<br />deck are you on?
      </h2>
      <p className="text-base md:text-lg text-white/50 max-w-2xl">
        Pick the portal that matches your role. Your dashboard, tools, and earnings will be tailored to it.
      </p>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
      {PORTALS.map((p) => {
        const active = selected === p.id;
        const Icon = p.icon;
        return (
          <button
            key={p.id}
            onClick={() => onSelect(p.id)}
            onDoubleClick={() => onConfirm(p.id)}
            className={cn(
              'manifest-card relative p-3 sm:p-5 text-left flex flex-row md:flex-col gap-3 sm:gap-4 transition-all border bg-white/[0.02] hover:bg-white/[0.05] md:min-h-[260px]',
              active ? 'border-white/40 scale-[1.01]' : 'border-white/10',
            )}
            style={active ? { borderColor: accent, boxShadow: `0 0 0 1px ${accent}, 0 30px 80px ${accent}33` } : undefined}
          >
            <div
              className="w-9 h-9 sm:w-11 sm:h-11 border flex items-center justify-center shrink-0 self-start"
              style={{ borderColor: active ? accent : 'rgba(255,255,255,0.1)' }}
            >
              <Icon className="w-4 h-4 sm:w-5 sm:h-5" style={{ color: active ? accent : 'rgba(255,255,255,0.5)' }} />
            </div>

            <div className="flex-1 min-w-0 flex flex-col gap-2 md:gap-3">
              <div>
                <div className="text-[9px] font-mono font-black uppercase tracking-[0.3em] italic mb-1" style={{ color: active ? accent : 'rgba(255,255,255,0.4)' }}>
                  {p.tagline}
                </div>
                <h3 className="text-base md:text-xl lg:text-2xl font-black italic uppercase tracking-tighter font-mono leading-none">
                  {p.name}
                </h3>
              </div>

              <p className="text-[11px] sm:text-xs text-white/60 leading-relaxed line-clamp-2 md:line-clamp-none">{p.desc}</p>

              <div className="hidden md:block space-y-1 pt-2 border-t border-white/5">
                {p.perks.map((perk) => (
                  <div key={perk} className="flex items-center gap-2 text-[10px] text-white/50">
                    <CheckCircle2 className="w-3 h-3 flex-shrink-0" style={{ color: accent }} />
                    <span>{perk}</span>
                  </div>
                ))}
              </div>
            </div>

            {active && (
              <div className="absolute top-4 right-4 flex items-center gap-2 text-[9px] font-mono font-black uppercase tracking-[0.3em] italic" style={{ color: accent }}>
                <CheckCircle2 className="w-4 h-4" />
                Selected
              </div>
            )}
          </button>
        );
      })}
    </div>

    <p className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-white/30 italic text-center">
      Tip — double-click a portal to enter directly, or hit "Enter Portal" below.
    </p>
  </div>
);

export default WelcomeScreen;
