import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useNavigate } from 'react-router-dom';
import {
  Rocket,
  Sparkles,
  Globe2,
  TrendingUp,
  Cpu,
  Camera,
  Radio,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  Sun,
  Moon,
  Zap,
  Palette,
  Users,
  Music,
  Disc,
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { useTheme, Vibe, UserRole, Theme } from '../../context/ThemeContext';

type SlideKind =
  | 'hero'
  | 'pitch'
  | 'feature'
  | 'color'
  | 'theme'
  | 'portal';

interface BaseSlide {
  id: string;
  kind: SlideKind;
}

const FEATURES = [
  {
    id: 'distribution',
    tag: 'PROTOCOL_01',
    title: 'Smart Distribution',
    desc: 'One upload. Every major DSP. Spotify, Apple, YouTube Music, Tidal, SoundCloud — distributed in parallel with live status telemetry on every platform.',
    icon: Rocket,
    accent: 'from-orange-500/20 to-transparent',
  },
  {
    id: 'ai',
    tag: 'PROTOCOL_02',
    title: 'AI Content Engine',
    desc: 'Cover art, video teasers, viral TikTok hooks, UGC scripts and promo packs — generated by neural pipelines tuned to your release.',
    icon: Sparkles,
    accent: 'from-blue-500/20 to-transparent',
  },
  {
    id: 'network',
    tag: 'PROTOCOL_03',
    title: 'Verified Creator Network',
    desc: 'Direct relays into a vetted network of influencers, micro-creators and DJs. Send packs, track posts, measure real reach — no middlemen.',
    icon: Globe2,
    accent: 'from-purple-500/20 to-transparent',
  },
  {
    id: 'lvrn',
    tag: 'PROTOCOL_04',
    title: 'LVRN Direct Access',
    desc: 'Submit to the LVRN A&R inner circle. Real feedback, strategic guidance, and direct lines to a label that has scaled platinum careers.',
    icon: TrendingUp,
    accent: 'from-green-500/20 to-transparent',
  },
];

const COLORS: { id: Vibe; name: string; hex: string; tagline: string }[] = [
  { id: 'TECHNICAL_ORANGE', name: 'Tech Orange', hex: '#FF4D00', tagline: 'Original manifest energy' },
  { id: 'LVRN_GREEN', name: 'LVRN Green', hex: '#acec00', tagline: 'Direct executive clearance' },
  { id: 'NEON_PINK', name: 'Neon Pink', hex: '#ff00ff', tagline: 'Hyperpop sonic frequency' },
  { id: 'CYBER_BLUE', name: 'Cyber Blue', hex: '#00f2ff', tagline: 'Cold digital logic' },
  { id: 'MONO_WHITE', name: 'Mono Archive', hex: '#ffffff', tagline: 'Minimal redacted aesthetic' },
];

const PORTALS: {
  id: UserRole;
  name: string;
  tagline: string;
  desc: string;
  icon: React.ElementType;
  route: string;
  perks: string[];
}[] = [
  {
    id: 'ARTIST',
    name: 'Artist Core',
    tagline: 'I make the music',
    desc: 'Full distribution, AI assets studio, campaign OS, and direct LVRN A&R submission.',
    icon: Music,
    route: '/signup',
    perks: ['Distribute to all DSPs', 'AI cover & video', 'A&R submission', 'Royalty splits'],
  },
  {
    id: 'INFLUENCER',
    name: 'Creator Relay',
    tagline: 'I create content',
    desc: 'Accept paid missions from artists, post on TikTok / Reels / Shorts, get paid per verified post.',
    icon: Camera,
    route: '/login',
    perks: ['Paid campaign missions', 'Performance analytics', 'Instant payouts', 'Brand match score'],
  },
  {
    id: 'DJ',
    name: 'Vibe Selecta',
    tagline: 'I move the dance floor',
    desc: 'Receive curated DJ promo packs, stem files, edits, and direct feedback loops to artists.',
    icon: Disc,
    route: '/login',
    perks: ['Exclusive DJ packs', 'Stems & edits access', 'Feedback channel', 'Chart signal data'],
  },
];

const SLIDES: BaseSlide[] = [
  { id: 'hero', kind: 'hero' },
  { id: 'pitch', kind: 'pitch' },
  ...FEATURES.map((f) => ({ id: f.id, kind: 'feature' as SlideKind })),
  { id: 'color', kind: 'color' },
  { id: 'theme', kind: 'theme' },
  { id: 'portal', kind: 'portal' },
];

const slideVariants = {
  enter: (dir: number) => ({ x: dir > 0 ? 80 : -80, opacity: 0 }),
  center: { x: 0, opacity: 1 },
  exit: (dir: number) => ({ x: dir > 0 ? -80 : 80, opacity: 0 }),
};

export const WelcomeScreen: React.FC<{ onComplete: () => void }> = ({ onComplete }) => {
  const navigate = useNavigate();
  const { vibe, setVibe, theme, toggleTheme, role, setRole } = useTheme();

  const [index, setIndex] = useState(0);
  const [direction, setDirection] = useState(1);

  const slide = SLIDES[index];
  const total = SLIDES.length;

  const next = () => {
    if (index < total - 1) {
      setDirection(1);
      setIndex((i) => i + 1);
    }
  };

  const prev = () => {
    if (index > 0) {
      setDirection(-1);
      setIndex((i) => i - 1);
    }
  };

  const finish = (route: string) => {
    onComplete();
    navigate(route);
  };

  const featureForSlide = useMemo(() => {
    if (slide.kind !== 'feature') return null;
    return FEATURES.find((f) => f.id === slide.id) || FEATURES[0];
  }, [slide]);

  const colorObj = COLORS.find((c) => c.id === vibe) ?? COLORS[0];

  return (
    <div
      className="welcome-container fixed inset-0 z-[200] flex flex-col bg-black text-white overflow-hidden"
      style={{ '--color-primary': colorObj.hex } as React.CSSProperties}
    >
      {/* Background */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute inset-0 technical-grid opacity-[0.04]" />
        <motion.div
          key={colorObj.hex}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.6 }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] rounded-full blur-[140px]"
          style={{ background: `radial-gradient(circle, ${colorObj.hex}22 0%, transparent 70%)` }}
        />
      </div>

      {/* Top bar */}
      <header className="relative z-10 flex items-center justify-between px-8 py-6">
        <div className="flex items-center gap-3">
          <div className="w-6 h-6 border flex items-center justify-center p-0.5" style={{ borderColor: colorObj.hex }}>
            <div className="w-full h-full" style={{ backgroundColor: colorObj.hex }} />
          </div>
          <span className="text-sm font-mono font-black tracking-tighter italic">DROPKAST</span>
          <span className="text-[9px] font-mono font-black text-white/30 tracking-[0.3em] uppercase italic ml-2">
            v3.0.1 — Onboarding
          </span>
        </div>

        <button
          onClick={onComplete}
          className="text-[10px] font-mono font-black text-white/30 hover:text-white tracking-[0.3em] uppercase italic flex items-center gap-2 group transition-colors"
        >
          <span>Skip Intro</span>
          <ChevronRight className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" />
        </button>
      </header>

      {/* Progress */}
      <div className="relative z-10 px-8 mb-2">
        <div className="flex gap-1 max-w-5xl mx-auto">
          {SLIDES.map((s, i) => (
            <div key={s.id} className="flex-1 h-[3px] bg-white/5 overflow-hidden">
              <motion.div
                className="h-full"
                style={{ backgroundColor: colorObj.hex }}
                initial={{ width: '0%' }}
                animate={{ width: i < index ? '100%' : i === index ? '100%' : '0%' }}
                transition={{ duration: 0.4 }}
              />
            </div>
          ))}
        </div>
        <div className="flex items-center justify-between max-w-5xl mx-auto mt-3 text-[9px] font-mono font-black text-white/30 tracking-[0.3em] uppercase italic">
          <span>
            Step {String(index + 1).padStart(2, '0')} / {String(total).padStart(2, '0')}
          </span>
          <span>{slide.kind.toUpperCase()}</span>
        </div>
      </div>

      {/* Slide body */}
      <main className="relative z-10 flex-1 overflow-y-auto px-8 pb-32">
        <div className="max-w-5xl mx-auto h-full flex items-center justify-center py-8">
          <AnimatePresence mode="wait" custom={direction}>
            <motion.div
              key={slide.id}
              custom={direction}
              variants={slideVariants}
              initial="enter"
              animate="center"
              exit="exit"
              transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
              className="w-full"
            >
              {slide.kind === 'hero' && <HeroSlide accent={colorObj.hex} />}

              {slide.kind === 'pitch' && <PitchSlide accent={colorObj.hex} />}

              {slide.kind === 'feature' && featureForSlide && (
                <FeatureSlide feature={featureForSlide} accent={colorObj.hex} />
              )}

              {slide.kind === 'color' && (
                <ColorSlide selected={vibe} onSelect={setVibe} colors={COLORS} accent={colorObj.hex} />
              )}

              {slide.kind === 'theme' && (
                <ThemeSlide theme={theme} onToggle={toggleTheme} accent={colorObj.hex} />
              )}

              {slide.kind === 'portal' && (
                <PortalSlide
                  selected={role}
                  onSelect={setRole}
                  onConfirm={(r) => {
                    setRole(r);
                    const portal = PORTALS.find((p) => p.id === r) ?? PORTALS[0];
                    finish(portal.route);
                  }}
                  accent={colorObj.hex}
                />
              )}
            </motion.div>
          </AnimatePresence>
        </div>
      </main>

      {/* Footer nav */}
      <footer className="absolute bottom-0 left-0 right-0 z-10 border-t border-white/5 bg-black/80 backdrop-blur-xl">
        <div className="max-w-5xl mx-auto px-8 py-5 flex items-center justify-between gap-4">
          <button
            onClick={prev}
            disabled={index === 0}
            className={cn(
              'h-12 px-6 border border-white/10 text-[10px] font-mono font-black uppercase italic tracking-[0.3em] flex items-center gap-3 transition-all',
              index === 0
                ? 'opacity-30 cursor-not-allowed'
                : 'hover:border-white hover:text-white text-white/50',
            )}
          >
            <ChevronLeft className="w-4 h-4" />
            Back
          </button>

          <div className="flex items-center gap-2 text-[9px] font-mono text-white/20 uppercase tracking-[0.3em] italic">
            <Zap className="w-3 h-3" style={{ color: colorObj.hex }} />
            <span>Press Next to continue</span>
          </div>

          {slide.kind !== 'portal' ? (
            <button
              onClick={next}
              className="h-12 px-8 text-[10px] font-mono font-black uppercase italic tracking-[0.3em] flex items-center gap-3 text-black transition-all hover:scale-[1.03]"
              style={{ backgroundColor: colorObj.hex }}
            >
              {index === 0 ? 'Begin' : 'Next'}
              <ArrowRight className="w-4 h-4" />
            </button>
          ) : (
            <button
              onClick={() => {
                const portal = PORTALS.find((p) => p.id === role) ?? PORTALS[0];
                finish(portal.route);
              }}
              className="h-12 px-8 text-[10px] font-mono font-black uppercase italic tracking-[0.3em] flex items-center gap-3 text-black transition-all hover:scale-[1.03]"
              style={{ backgroundColor: colorObj.hex }}
            >
              Enter Portal
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      </footer>
    </div>
  );
};

/* ---------------- Slide bodies ---------------- */

const HeroSlide: React.FC<{ accent: string }> = ({ accent }) => (
  <div className="text-center md:text-left space-y-10">
    <div className="flex items-center justify-center md:justify-start gap-4">
      <div className="h-[1px] w-12" style={{ backgroundColor: accent }} />
      <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
        System Initiated
      </span>
    </div>
    <h1 className="text-6xl md:text-9xl font-black italic uppercase tracking-tighter font-mono leading-[0.85]">
      <span className="block">DROP</span>
      <span className="block" style={{ color: accent }}>KAST</span>
    </h1>
    <p className="max-w-2xl text-lg md:text-2xl text-white/60 leading-relaxed font-medium">
      The AI-powered command deck for independent music. Distribute to every DSP, generate viral content, deploy
      verified creator networks, and submit straight to LVRN A&R — all from one launchpad.
    </p>
    <div className="flex flex-wrap items-center justify-center md:justify-start gap-x-6 gap-y-2 text-[10px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic">
      <span>Distribution</span>
      <span style={{ color: accent }}>•</span>
      <span>AI Content</span>
      <span style={{ color: accent }}>•</span>
      <span>Creator Network</span>
      <span style={{ color: accent }}>•</span>
      <span>A&R Pipeline</span>
    </div>
  </div>
);

const PitchSlide: React.FC<{ accent: string }> = ({ accent }) => (
  <div className="space-y-12">
    <div className="space-y-4">
      <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
        What Is DropKast?
      </span>
      <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-none">
        Music distribution<br /> built for the<br />
        <span style={{ color: accent }}>algorithm era.</span>
      </h2>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      {[
        {
          k: 'For Artists',
          v: 'Upload once. Hit every DSP. Get a campaign OS that thinks for you.',
          icon: Rocket,
        },
        {
          k: 'For Creators',
          v: 'Get paid for posts. Match with the right releases. Track every metric.',
          icon: Sparkles,
        },
        {
          k: 'For DJs',
          v: 'First-look promo packs, stems, and edits direct from the source.',
          icon: Radio,
        },
      ].map((b) => (
        <div key={b.k} className="manifest-card p-6 border-white/10 bg-white/[0.02]">
          <b.icon className="w-6 h-6 mb-4" style={{ color: accent }} />
          <div className="text-[10px] font-mono font-black uppercase tracking-[0.3em] text-white/40 italic mb-2">
            {b.k}
          </div>
          <p className="text-sm text-white/80 leading-relaxed">{b.v}</p>
        </div>
      ))}
    </div>
  </div>
);

const FeatureSlide: React.FC<{ feature: typeof FEATURES[number]; accent: string }> = ({ feature, accent }) => {
  const Icon = feature.icon;
  return (
    <div className="grid grid-cols-1 md:grid-cols-12 gap-12 items-center">
      <div className="md:col-span-5 flex justify-center md:justify-start">
        <div
          className="relative w-48 h-48 md:w-64 md:h-64 border-2 flex items-center justify-center"
          style={{ borderColor: accent }}
        >
          <div
            className="absolute inset-0 opacity-10"
            style={{ background: `radial-gradient(circle, ${accent} 0%, transparent 70%)` }}
          />
          <Icon className="w-24 h-24 md:w-32 md:h-32 relative z-10" style={{ color: accent }} />
          <div
            className="absolute -top-3 -left-3 text-[9px] font-mono font-black uppercase tracking-[0.3em] italic px-2 py-1 bg-black"
            style={{ color: accent }}
          >
            {feature.tag}
          </div>
        </div>
      </div>

      <div className="md:col-span-7 space-y-6">
        <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-[0.9]">
          {feature.title}
        </h2>
        <p className="text-lg md:text-xl text-white/60 leading-relaxed font-medium">{feature.desc}</p>
        <div className="flex items-center gap-3 text-[10px] font-mono font-black uppercase tracking-[0.4em] italic" style={{ color: accent }}>
          <Zap className="w-4 h-4" />
          <span>Ready to deploy</span>
        </div>
      </div>
    </div>
  );
};

const ColorSlide: React.FC<{
  selected: Vibe;
  onSelect: (v: Vibe) => void;
  colors: typeof COLORS;
  accent: string;
}> = ({ selected, onSelect, colors, accent }) => (
  <div className="space-y-10">
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <Palette className="w-4 h-4" style={{ color: accent }} />
        <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
          Pick Your Color
        </span>
      </div>
      <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-none">
        Choose your<br />signature accent.
      </h2>
      <p className="text-base md:text-lg text-white/50 max-w-2xl">
        This is the color that will pulse through every button, chart, and notification across DropKast. You can change it
        any time from settings.
      </p>
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
      {colors.map((c) => {
        const active = selected === c.id;
        return (
          <button
            key={c.id}
            onClick={() => onSelect(c.id)}
            className={cn(
              'manifest-card relative p-5 text-left transition-all border bg-white/[0.02] hover:bg-white/[0.04]',
              active ? 'border-white/40' : 'border-white/10',
            )}
            style={active ? { borderColor: c.hex, boxShadow: `0 0 0 1px ${c.hex}, 0 20px 60px ${c.hex}33` } : undefined}
          >
            <div
              className="w-full aspect-square mb-4 rounded-sm"
              style={{
                background: `linear-gradient(135deg, ${c.hex} 0%, ${c.hex}88 100%)`,
                boxShadow: `inset 0 0 30px rgba(0,0,0,0.3)`,
              }}
            />
            <div className="text-sm font-mono font-black uppercase tracking-tight italic">{c.name}</div>
            <div className="text-[9px] font-mono font-bold uppercase tracking-[0.2em] text-white/40 italic mt-1">
              {c.tagline}
            </div>
            {active && (
              <div className="absolute top-3 right-3">
                <CheckCircle2 className="w-4 h-4" style={{ color: c.hex }} />
              </div>
            )}
          </button>
        );
      })}
    </div>
  </div>
);

const ThemeSlide: React.FC<{ theme: Theme; onToggle: () => void; accent: string }> = ({ theme, onToggle, accent }) => {
  const setTheme = (target: Theme) => {
    if (theme !== target) onToggle();
  };

  return (
    <div className="space-y-10">
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          {theme === 'dark' ? <Moon className="w-4 h-4" style={{ color: accent }} /> : <Sun className="w-4 h-4" style={{ color: accent }} />}
          <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
            Pick Your Theme
          </span>
        </div>
        <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-none">
          Light mode<br />or dark mode?
        </h2>
        <p className="text-base md:text-lg text-white/50 max-w-2xl">
          Default is dark — the way the studio runs at 3am. Switch to light if you live in spreadsheets.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl">
        {([
          {
            id: 'dark' as Theme,
            name: 'Dark Mode',
            tagline: 'Studio default',
            preview: 'bg-black',
            accentBox: 'bg-white/10',
            text: 'text-white',
            sub: 'text-white/40',
            icon: Moon,
          },
          {
            id: 'light' as Theme,
            name: 'Light Mode',
            tagline: 'Daylight ops',
            preview: 'bg-neutral-100',
            accentBox: 'bg-black/10',
            text: 'text-black',
            sub: 'text-black/40',
            icon: Sun,
          },
        ]).map((t) => {
          const active = theme === t.id;
          const Icon = t.icon;
          return (
            <button
              key={t.id}
              onClick={() => setTheme(t.id)}
              className={cn(
                'manifest-card relative p-6 text-left transition-all border bg-white/[0.02] hover:bg-white/[0.04]',
                active ? 'border-white/40' : 'border-white/10',
              )}
              style={active ? { borderColor: accent, boxShadow: `0 0 0 1px ${accent}, 0 20px 60px ${accent}22` } : undefined}
            >
              <div className={cn('w-full h-32 mb-5 rounded-sm flex items-end p-4', t.preview)}>
                <div className="w-full space-y-2">
                  <div className={cn('h-2 w-1/3', t.accentBox)} />
                  <div className={cn('h-2 w-2/3', t.accentBox)} />
                  <div className="h-2 w-1/4" style={{ backgroundColor: accent }} />
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2">
                    <Icon className="w-4 h-4" style={{ color: active ? accent : 'rgba(255,255,255,0.6)' }} />
                    <span className="text-base font-mono font-black uppercase italic">{t.name}</span>
                  </div>
                  <div className="text-[9px] font-mono font-bold uppercase tracking-[0.2em] text-white/40 italic mt-1">
                    {t.tagline}
                  </div>
                </div>
                {active && <CheckCircle2 className="w-5 h-5" style={{ color: accent }} />}
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
};

const PortalSlide: React.FC<{
  selected: UserRole;
  onSelect: (r: UserRole) => void;
  onConfirm: (r: UserRole) => void;
  accent: string;
}> = ({ selected, onSelect, onConfirm, accent }) => (
  <div className="space-y-10">
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <Users className="w-4 h-4" style={{ color: accent }} />
        <span className="text-[10px] font-mono font-black tracking-[0.4em] uppercase italic" style={{ color: accent }}>
          Choose Your Portal
        </span>
      </div>
      <h2 className="text-4xl md:text-6xl font-black italic uppercase tracking-tighter font-mono leading-none">
        Which side of the<br />deck are you on?
      </h2>
      <p className="text-base md:text-lg text-white/50 max-w-2xl">
        Pick the portal that matches your role. Your dashboard, tools, and earnings will be tailored to it.
      </p>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      {PORTALS.map((p) => {
        const active = selected === p.id;
        const Icon = p.icon;
        return (
          <button
            key={p.id}
            onClick={() => onSelect(p.id)}
            onDoubleClick={() => onConfirm(p.id)}
            className={cn(
              'manifest-card relative p-7 text-left flex flex-col gap-5 transition-all border bg-white/[0.02] hover:bg-white/[0.05] min-h-[420px]',
              active ? 'border-white/40 scale-[1.01]' : 'border-white/10',
            )}
            style={active ? { borderColor: accent, boxShadow: `0 0 0 1px ${accent}, 0 30px 80px ${accent}33` } : undefined}
          >
            <div
              className="w-14 h-14 border flex items-center justify-center"
              style={{ borderColor: active ? accent : 'rgba(255,255,255,0.1)' }}
            >
              <Icon className="w-7 h-7" style={{ color: active ? accent : 'rgba(255,255,255,0.5)' }} />
            </div>

            <div>
              <div className="text-[10px] font-mono font-black uppercase tracking-[0.3em] italic mb-2" style={{ color: active ? accent : 'rgba(255,255,255,0.4)' }}>
                {p.tagline}
              </div>
              <h3 className="text-2xl md:text-3xl font-black italic uppercase tracking-tighter font-mono leading-none">
                {p.name}
              </h3>
            </div>

            <p className="text-sm text-white/60 leading-relaxed">{p.desc}</p>

            <div className="mt-auto space-y-2 pt-4 border-t border-white/5">
              {p.perks.map((perk) => (
                <div key={perk} className="flex items-center gap-2 text-[11px] text-white/50">
                  <CheckCircle2 className="w-3.5 h-3.5 flex-shrink-0" style={{ color: accent }} />
                  <span>{perk}</span>
                </div>
              ))}
            </div>

            {active && (
              <div className="absolute top-4 right-4 flex items-center gap-2 text-[9px] font-mono font-black uppercase tracking-[0.3em] italic" style={{ color: accent }}>
                <CheckCircle2 className="w-4 h-4" />
                Selected
              </div>
            )}
          </button>
        );
      })}
    </div>

    <p className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-white/30 italic text-center">
      Tip — double-click a portal to enter directly, or hit "Enter Portal" below.
    </p>
  </div>
);

export default WelcomeScreen;
